### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by merwok** [rabbit72/single-source#2]
Hello!  I read the readme and don’t understand how this is supposed to work.

Dev files like pyproject.toml are not installed, so how do you find the version at runtime?

**Comment by rabbit72** [comment]
Hello! The logic is pretty simple.
You just provide it your package name then it tries to loot at `importlib_metadata.version`
`version = importlib_metadata.version(package_name)`
If it didn't find a version, then the library tries to extract the version from `pyproject.toml`

The first method is used when you have your package installed (usually `pip install`) by your users. It doesn't matter whether pyproject.toml is presented in your package or not.

Let's imagine. I want to use the version (I mean the value) of my package in some place in the code. I don't want to have it in some python file (as a string) and pyproject.toml at the same time. It's harder to maintain and easier to forget. 
Also, I don't want to build the wheel by creating some bumping version script and use`poetry version patch` or `poetry version prerelease` commands instead.

The first method doesn't work when you develop and don't have the libarary installed (`poerty install --no-root`)

**Comment by merwok** [comment]
Ah so it’s not single-source!  For libraries or any code that’s a dependency, devs need to write code that tries `importlib.metadata.version(name)` first, falls back to `importlib_metadata` for older Python versions, then falls back to using this project for the uninstalled use case or when building a dist.

**Comment by rabbit72** [comment]
So, you described exactly how it works. The decision of the usage a newer importlib.metadata or an older importlib_metadata is resolved when it's imported

**Comment by l0b0** [comment]
Working example from a file in a project child directory:

```python
# Only works in dev env
version_string = get_version(__name__, Path(__file__).parent.parent)
if not version_string:  # pragma: no cover
    # Only works when package is installed
    version_string = version("package_name")
```
