### ISSUE TITLE
mypy reports "Skipping analyzing 'single_source': found module but no type hints or library stubs"

### ISSUE THREAD

**Issue by erny** [rabbit72/single-source#3]
Thanks for this cool piece of software.

Could you please add an empty file py.typed as per [PEP 561 packaging](https://www.python.org/dev/peps/pep-0561/#id18) ?

Thanks.

**Comment by rabbit72** [comment]
Thanks for opening the issue. That's really cool!
Adding `py.typed` file would be not enough for the successful integration with mypy. 
I'll add mypy to the project and resolve the issues it finds

I do appreciate your attention to the library.
