### ISSUE TITLE
'default_return=None' does not work it was intended as (it seems)

### ISSUE THREAD

**Issue by hotenov** [rabbit72/single-source#6]
It seems logic for keyword 'default_return=None' could be improved.

As I understood, passing `default_return=None` we tell function to ignore version from `importlib_metadata.version(package_name)` and to use version from `pyproject.toml`.  

And here is my problem:

As I noticed from source code we never go through the line #61  
_(for examples in README and because during poetry project initialization we set initial version and it will be saved in package meta info when we do the first `poetry install`)_ :  
![image](https://user-images.githubusercontent.com/11818507/116507017-281ed680-a8c7-11eb-9548-2fe67c5b8f7d.png)

And to pass through it we had to pass our package name with random name, i.e.  
_(three `.parent` cause I use "src layout" for my package)_

```python
__version__ = get_version("fake-package", Path(__file__).parent.parent.parent)
```  
That works :) BUT this is not an obvious workaround.

Maybe the condition  should be:

```python
if version is None or default_return is None:
```
or something like this 🙂

P.S. Thanks for this library 👍

**Comment by hotenov** [comment]
No. That's a bad idea I forgot that there is now any `pyproject.toml` file in the installed package :)

But, maybe, there is a reason to change order of checking:  
first, in `pyproject.toml` _(if it exists)_   
second, in `importlib_metadata.version(package_name)`

It would solve a problem with running script without installation (during development and using poetry scripts). Or I'm wrong again?

**Comment by rabbit72** [comment]
hi @hotenov ,
Glad to hear that it is helping someone else.

`default_return` is responsible for the value that would be returned if both, installed package and `pyproject.toml`,  absent.

Probably I see the problem here. Do you have your library installed when you are developing?
What's your use case? When is the priority of the version from `pyproject.toml` important?

**Comment by hotenov** [comment]
Hi! @rabbit72 

I use poetry scripts (entry points) for debugging and development, for example:

```toml
[tool.poetry.scripts]
my-script = "package_name.__main__:main"
```

and run it in terminal as `poetry run my-script`

In this case, I can view changes immediately after saving a code file. Without installing package into .venv or somewhere else. But this way has disadvantage: I always have initial project (package) version, i.e. `0.0.0` or `0.0.1`.  
That causes failed unit-tests in VS Code runner (where version is needed) and of cause in terminal I see initial version.

It would be nice to have version detection with `pyproject.toml` first. Then my IDE and terminal would take current version. When code is running in .venv _(or CI jobs)_ - package would be installed and code would get version from package metadata (because there is no `pyproject.toml`)

That's it. I could explain in Russian more detailed :) if it still unclear.

**Comment by hotenov** [comment]
**UPD:** as temporary solution for me, I added this condition in my `__init__.py` file, based on your code :)

```python
# __init__.py
from pathlib import Path

from single_source import get_version

pyproject_name = "pyproject.toml"
path_to_project_dir = Path(__file__).parent.parent.parent
target_path = path_to_project_dir
target_path /= pyproject_name

if target_path.exists():
    __version__ = get_version("fake-package", path_to_project_dir)
else:
    __version__ = get_version(__name__, Path(__file__).parent)
```

Very ugly code, but it works =)

Now you can close my issue (or tell me to close), if you think that is not worth implementing for all library users :)

**Comment by rabbit72** [comment]
Actually, I think it makes sense to change the order. I haven't thought about it because I don't have my package installed in a virtual environment where I develop.
It can be done with --no-root flag in poetry.
Give me a bit more time for consideration.

Thank you.

**Comment by rabbit72** [comment]
hi @hotenov,

A new version of the library is available. (v0.2.0)
The version from `pyproject.toml` has priority over the extracted from the environment.
Thanks for your idea.

**Comment by hotenov** [comment]
Well done! Thanks a lot! 

I've just upgraded to `0.2.0` version. Now, my code is short again. I mention it here for new googlers and who also use `src` layout and debug with `poetry run`

```python
# __init__.py

from pathlib import Path

from single_source import get_version

path_to_project_dir = Path(__file__).parent.parent.parent
__version__ = get_version(__name__, path_to_project_dir)

```
